### ISSUE TITLE
mysqltools8里，怎么没有主从安装那些了？

### ISSUE THREAD

**Issue by bobzhanggmail** [Neeky/mysqltools8#2]
你好，想问下，mysqltools8里，我看只有单机实例的安装。
主从那些是去掉了吗？如果要恢复支持主从，大概要怎么弄？
谢谢！

**Comment by Neeky** [comment]
这段时间工作上的内容比较多，之后闲下来了会给它增加上。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"frank zhang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月29日(星期二) 下午3:45
收件人:&nbsp;"Neeky/mysqltools8"<mysqltools8@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Neeky/mysqltools8] mysqltools8里，怎么没有主从安装那些了？ (#2)




你好，想问下，mysqltools8里，我看只有单机实例的安装。
 主从那些是去掉了吗？如果要恢复支持主从，大概要怎么弄？
 谢谢！

**Comment by bobzhanggmail** [comment]
> 这段时间工作上的内容比较多，之后闲下来了会给它增加上。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"frank zhang"<notifications@github.com&gt;; 发送时间:&nbsp;2019年10月29日(星期二) 下午3:45 收件人:&nbsp;"Neeky/mysqltools8"<mysqltools8@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[Neeky/mysqltools8] mysqltools8里，怎么没有主从安装那些了？ (#2) 你好，想问下，mysqltools8里，我看只有单机实例的安装。 主从那些是去掉了吗？如果要恢复支持主从，大概要怎么弄？ 谢谢！ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

好的，谢谢！

**Comment by Neeky** [comment]
@bobzhanggmail  HI 看这里 https://github.com/Neeky/dbm-agent 所有 mysql-8.0.x 的功能都支持上去了。

**Comment by Neeky** [comment]
1、单机
2、主从
3、MGR
4、mysql-shell  innodb-cluster mysql-router 
这一切都有
